// Auto-generated by scripts/build-wasm.js - do not edit manually
// Rebuild with: pnpm wasm:build
// Placeholder - run pnpm wasm:build after implementing assembly/index.ts

export const AI_WASM_BASE64 = ''
